#!/usr/bin/env ruby
lib = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require "pr_summary"

PrSummary.call(pull_request_number:  (ENV["PR_NUM"] || ARGV[0]).chomp, branch: (ENV["BRANCH"] || ARGV[1]).chomp, base: (ENV["BASE"] || ARGV[2]).chomp)
